### ISSUE TITLE
New School Addition for Yogyakarta

### ISSUE THREAD

**Issue by Dito25** [Dito25/Dito#1]
Kindly need your help to add new school for Yogyakarta

detail of school can be found here
https://docs.google.com/spreadsheets/d/1A5e0J1toYwNIcXrGfNkyg_HHFz40swWtDTE-cln7FGE/edit#gid=228236770

@bebichrisyanti @malik @hananifaiza @yfunase @tmizusawa @takuya514

**Comment by hananifaiza** [comment]
Hi  pak @Dito25 

All schools are added. If all are okay, you can close this issue. But for next time, please create issue in quipper/indonesia (https://github.com/quipper/indonesia).

Thank you

**Comment by Dito25** [comment]
thanks Mbak @hananifaiza 
very well noted mbak
thanks for reminding
